# Generated by Django 4.0.4 on 2022-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='reviewer',
            new_name='purchaser',
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
